### ISSUE TITLE
fetchData is missing

### ISSUE THREAD

**Issue by janbaer** [MangroveTech/co-inbox#3]
How can I fetch the message by the Id? The Inbox library that you use provides a function named fetchData where I can fetch the message with the body by the UID.

**Comment by yorkie** [comment]
Thanks @janbaer I have supported this method `fetchData` and will publish to npm soon later :-)

**Comment by yorkie** [comment]
Bumped new version: [co-inbox@1.1.0](https://npmjs.org/co-inbox) :beers:

**Comment by janbaer** [comment]
Thanks for the fast feedback! Will test ist tomorrow :-)
